#ifndef WHX_SOCKET_H
#define WHX_SOCKET_H
#include "tdevice.h"
#include <sys/ioctl.h>

#define SOCKET_STREAM_TYPE 0
#define SOCKET_DGRAM_TYPE  1


#ifdef		TDM_SI_CPLUSPLUS
extern	"C"{
#endif		/*TDM_SI_CPLUSPLUS*/

TDM_TDEVICEAPI	TDBOOL		TDSocketInit();
TDM_TDEVICEAPI	TDBOOL		TDSocketDestroy();

TDM_TDEVICEAPI	TDHANDLE	TDSocketOpen(TDPString pHost,TDINT in_port,TDINT svr_port,TDINT type);
TDM_TDEVICEAPI	TDDWORD		TDAddressExist(TDCHAR* url);
TDM_TDEVICEAPI	TDVOID		TDSocketClose(TDHANDLE socket);
TDM_TDEVICEAPI	TDDWORD		TDSocketRead(TDHANDLE hFile,TDPVOID pBuf,TDDWORD BytesToRead);
TDM_TDEVICEAPI	TDDWORD		TDSocketWrite(TDHANDLE hFile,TDPVOID pBuf,TDDWORD BytesToRead);
TDM_TDEVICEAPI	TDDWORD		TDSocketReadUntilDone(TDHANDLE hFile,TDPVOID pBuf,TDDWORD BytesToRead);
TDM_TDEVICEAPI	TDDWORD		TDSocketWriteUntilDone(TDHANDLE hFile,TDPVOID pBuf,TDDWORD BytesToRead);
TDM_TDEVICEAPI	TDWORD		TDSocketGetLocalPort(TDHANDLE hFile);
TDM_TDEVICEAPI	TDBOOL		TDSocketReadyRead(TDHANDLE hFile);
TDM_TDEVICEAPI	TDBOOL		TDSocketSetRecvTimeout(TDHANDLE hFile,TDINT nms);
TDM_TDEVICEAPI	TDBOOL		TDSocketSetServeraddr(TDHANDLE hFile,TDDWORD IPaddr,TDSHORT nPort);
TDM_TDEVICEAPI	TDINT		TDSocketGetMsgLen(TDHANDLE hFile);
TDM_TDEVICEAPI	TDDWORD		TDSocketBlockRead(TDHANDLE hFile,TDPVOID pBuf,TDDWORD BytesToRead);
TDM_TDEVICEAPI	TDBOOL		TDFindDefaultUrl(TDPCHAR url);
TDM_TDEVICEAPI	TDBOOL		TDFindHttpProxy();

TDM_TDEVICEAPI	TDINT		TDSetNoBlockSatus(TDHANDLE hFile);

TDM_TDEVICEAPI	TDVOID TDDebugInfo(TDCHAR *buf);
#ifdef		TDM_SI_CPLUSPLUS
}
#endif		/*TDM_SI_CPLUSPLUS*/
#endif

